### ISSUE TITLE
me again

### ISSUE THREAD

**Issue by simon511000** [mitchellurgero/jsondatabase#1]
Hello,
Once again, I would like to congratulate you for your tremendous work.
This script is 100% functional, very complete and very simple.
Thanks to you, I would not have to mess with MySQL anymore.
I just have a question: what are the "tmp" and "gc" folders for?
And what about "WHERE" and "EQUALS" in :
select("TABLE_NAME", "**WHERE**" = null, "**EQUALS**" = null);

**Comment by mitchellurgero** [comment]
select("USERS", "username","simon")

USERS = table name ("TABLE_NAME")
username = column name("WHERE")
simon = what you are looking for("EQUALS")

tmp and gc are not used yet but as I add and optimize this PHP they will be used for caching and garbage collection.
