### ISSUE TITLE
licence

### ISSUE THREAD

**Issue by simon511000** [mitchellurgero/jsondatabase#2]
Hello, I want to use your script for my projects.
Unfortunately, I did not find the LICENSE, what is the license please?

**Comment by mitchellurgero** [comment]
Oh my gosh, yea it is licensed under MIT. Feel free to use it however you like :)

**Comment by simon511000** [comment]
thank you very much ^^

**Comment by mitchellurgero** [comment]
I updated the license file in the repo as well so don't forget to pull

**Comment by simon511000** [comment]
yes, tank !
