### ISSUE TITLE
auto increment

### ISSUE THREAD

**Issue by simon511000** [mitchellurgero/jsondatabase#3]
small suggestion: add auto increment

**Comment by mitchellurgero** [comment]
Auto increment for what? insert already does this.

**Comment by simon511000** [comment]
yes, but add a value that increases from 1 to each selects. As in MySQL.

**Comment by mitchellurgero** [comment]
Can you give me an example MySQL query that uses that? I am having difficulty understanding you.

**Comment by simon511000** [comment]
Ok, 
`CREATE TABLE Persons (
ID int NOT NULL **AUTO_INCREMENT**,
LastName varchar(255) NOT NULL,
FirstName varchar(255),
Address varchar(255),...`
![](https://framapic.org/Owg9Mtclgvnp/acip4nDWlRBj)

**Comment by mitchellurgero** [comment]
$row['row_id'] Already auto increments, however if you specify a row during insert ($db->insert($data, 42);) it will not auto increment. (row_id being ID in the screenshot you sent) row_id exists automatically and does not need to be touch by you (unless you change it during runtime). every row will always have that variable.

**Comment by simon511000** [comment]
Yes, tank you !!
that's exactly what I needed

**Comment by mitchellurgero** [comment]
Awesome! Let me know if you need anything else!
