### ISSUE TITLE
array

### ISSUE THREAD

**Issue by simon511000** [mitchellurgero/jsondatabase#4]
idea of update that would be very useful to me: that the array work

**Comment by mitchellurgero** [comment]
The array work?

`$db->insert("table1",json_encode($nameOfArray));` ??

**Comment by simon511000** [comment]
non, the array don’t work : 
`
$data["devoir"]["classe"] = [
    "1" => "6emeA",
    "2" => "6emeC",
    "3" => "3emeA",
    "4" => "TS"
];

$data = json_encode($data);
$bdd->insert("devoirs", $data);
and : 
print_r($bdd->select("devoirs"));
`

**Comment by mitchellurgero** [comment]
Ah I see the issue. try not using multi-dimensional array's or:

$bdd->insert("devoirs", json_encode($data['devoir']));

**Comment by simon511000** [comment]
Ok, tank

**Comment by mitchellurgero** [comment]
Unrelated: Check https://github.com/mitchellurgero/tinysocial it uses JSONDatabase in a neat way.

Also JSONDatabase has been updated to fix a couple bugs.
